# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ethernet_lite.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_ethernetlite_0_0/design_1_axi_ethernetlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_ethernetlite_0_0 || ORIG_REF_NAME==design_1_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_eth_tx_master_0_0/design_1_eth_tx_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_eth_tx_master_0_0 || ORIG_REF_NAME==design_1_eth_tx_master_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_counter_0_0/design_1_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_counter_0_0 || ORIG_REF_NAME==design_1_counter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1 || ORIG_REF_NAME==design_1_clk_wiz_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reset_inv_0_2/design_1_reset_inv_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reset_inv_0_2 || ORIG_REF_NAME==design_1_reset_inv_0_2} -quiet] -quiet

# XDC: /home/ryadav/work_amd/Ethernet_Arty/Vivado/Vivado.gen/sources_1/bd/design_1/design_1_ooc.xdc
